services:
  server:
    build: ./server
    container_name: django-server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./server:/server_app
    env_file:
      - .env

  client:
    build: ./client
    container_name: react-client
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://0.0.0.0:8000/api
    depends_on:
      - server
